export const APP_NAMES = {
  containerApp: 'Home',
  notifications: 'Notifications',
  calendar: 'Calendar',
  timeTracking: 'Time Tracking',
  email: 'Email',
  liveChat: 'Live Chat',
  projectManagement: 'Project Management',
  taskManagement: 'Task Management',
  hr: 'HR',
  files: 'Files',
  office: 'Office',
  pdf: 'PDF',
  companySearcher: 'Company Searcher',
  noCode: 'No Code',
  templateManager: 'Template Manager',
  accounting: 'Accounting',
  subsidies: 'Subsidies',
  bulkMailing: 'Bulk Mailing',
  customers: 'Customers',
  externalForms: 'External Forms',
  byteBuilder: 'Byte Builder',
  integration: 'Integration',
}
