export const URLs = {
  calendar: '/calendar',
  timeTracking: '/time-tracking',
  email: '/email',
  liveChat: '/live-chat',
  projectManagement: '/project-management/projects/overview',
  taskManagement: '/task-management',
  hrDashboard: '/hr/dashboard',
  files: '/cluster-space',
  office: '/cluster-office',
  pdf: '/cluster-pdf',
  companySearcher: '/company-search/company',
  noCode: '/no-code/dashboard/overview',
  templateManager: '/template-manager',
}
